services:
  tennis:
    build:
      context: .
      dockerfile: Tennis/Dockerfile
    ports:
      - 7171:7171
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=tennis
